#!/usr/bin/python
import sys
import math
i = 0
p = 0
z = 0

def isprime(n):
	if n < 2:
		return False
	for i in range(2, n//2 + 1):
		if (n % i) == 0:
			return False
	return True

while True:
	if isprime(i):
		p = i
		z = z + 1
	if z == int(sys.argv[1]):
		print p
		exit(0)
	i = i + 1
